name: amardokan
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  local_auth: ^3.0.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  device_info_plus: ^13.2.0
  google_mobile_ads: ^9.1.0
  pdf: ^3.11.1
  printing: ^5.13.2
  mobile_scanner: ^7.4.0
  firebase_storage: ^13.5.0
  connectivity_plus: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#0D47A1" # আপনার অ্যাপের থিম কালার (নীল)
  adaptive_icon_foreground: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true

  # এখানে আপনার লোগো বা ছবির অ্যাসেট পাথ যোগ করা হয়েছে
  assets:
    - assets/images/ic_launcher.png
    - assets/images/login_bg.png

  fonts:
    - family: SolaimanLipi
      fonts:
        - asset: assets/fonts/SolaimanLipi-Normal.ttf
        - asset: assets/fonts/SolaimanLipi-Bold.ttf
          weight: 700